"""
Prompt builder for generating WhatsApp marketing messages.

This prompt instructs the LLM to create a short, natural, and
engaging WhatsApp message for Indian small businesses.
"""


def build_whatsapp_prompt(
    business_profile: dict,
    strategy: dict,
    wa_language: str,
) -> str:
    """
    Build the prompt for the WhatsApp Copy Writer node.

    Args:
        business_profile: Structured business information.
        strategy: Marketing strategy generated by the Strategy Planner.
        wa_language: Language in which the WhatsApp message should be written.

    Returns:
        A formatted prompt string for the Mistral model.
    """

    return f"""
You are an expert copywriter for Indian small businesses.

Your task is to write a WhatsApp marketing message that feels natural,
friendly, and personal.

Business Profile:

{business_profile}

Marketing Strategy:

{strategy}

Target Language:

{wa_language}

Rules:

- Write ONLY in the requested language.
- Keep the message between 4 and 6 lines.
- Use simple words that anyone can understand.
- Make it sound like it was written by the business owner.
- Include the offer if one exists.
- End with ONE clear call-to-action.
- Use at most 3 emojis.
- Never use corporate or technical marketing terms.
- Do NOT include markdown.
- Do NOT include explanations.
- Return ONLY the WhatsApp message.
"""