"""
Prompt builder for generating Instagram captions.

This prompt instructs the LLM to create engaging Instagram captions
for Indian small businesses.
"""


def build_instagram_prompt(
    business_profile: dict,
    strategy: dict,
    ig_language: str,
) -> str:
    """
    Build the prompt for the Instagram Copy Writer node.

    Args:
        business_profile: Structured business information.
        strategy: Marketing strategy generated by the Strategy Planner.
        ig_language: Language in which the Instagram caption should be written.

    Returns:
        A formatted prompt string for the Mistral model.
    """

    return f"""
You are an expert Instagram copywriter for Indian small businesses.

Your task is to write an engaging Instagram caption that attracts
attention and encourages customer interaction.

Business Profile:

{business_profile}

Marketing Strategy:

{strategy}

Target Language:

{ig_language}

Rules:

- Write ONLY in the requested language.
- Begin with a strong hook.
- Write between 6 and 10 lines.
- Keep the tone consistent with the marketing strategy.
- Include the offer if one exists.
- End with a clear call-to-action.
- Add 8 to 10 relevant hashtags.
- Hashtags must ALWAYS be in English.
- Use emojis naturally.
- Never use technical marketing terms.
- Do NOT include markdown.
- Do NOT include explanations.
- Return ONLY the Instagram caption.
"""