"""
Prompt builder for the Quality Checker node.

This prompt instructs the LLM to review the generated
WhatsApp message and Instagram caption for quality,
consistency, and marketing effectiveness.
"""


def build_quality_checker_prompt(
    business_profile: dict,
    strategy: dict,
    whatsapp_copy: str,
    instagram_caption: str,
    wa_language: str,
    ig_language: str,
) -> str:
    """
    Build the prompt for the Quality Checker node.

    Args:
        business_profile: Structured business information.
        strategy: Marketing strategy generated by the Strategy Planner.
        whatsapp_copy: Generated WhatsApp marketing message.
        instagram_caption: Generated Instagram caption.
        wa_language: Expected WhatsApp language.
        ig_language: Expected Instagram language.

    Returns:
        A formatted prompt string for the Mistral model.
    """

    return f"""
You are a senior marketing quality reviewer for Indian small businesses.

Your task is to review the generated marketing copy and determine
whether it satisfies the campaign requirements.

Business Profile:

{business_profile}

Marketing Strategy:

{strategy}

WhatsApp Copy:

{whatsapp_copy}

Instagram Caption:

{instagram_caption}

Expected WhatsApp Language:

{wa_language}

Expected Instagram Language:

{ig_language}

Review Checklist:

1. Does the copy match the business goal?
2. Does it follow the marketing strategy?
3. Is the tone appropriate?
4. Is the WhatsApp message personal and natural?
5. Does the Instagram caption begin with a strong hook?
6. Does the Instagram caption include relevant hashtags?
7. Are both outputs written in the correct language?
8. Is the offer included when available?
9. Are there any obvious grammar or spelling mistakes?

Rules:

- Return ONLY valid JSON.
- Do NOT include markdown.
- Do NOT include explanations.
- Do NOT include code fences.

Return exactly this JSON format:

{{
    "passed": true,
    "score": 9,
    "feedback": "Short explanation of the review."
}}
"""