"""
Prompt builder for the Strategy Planner node.

This prompt instructs the LLM to analyze a structured business profile
and generate a marketing strategy for the campaign.
"""


def build_strategy_prompt(
    business_profile: dict,
) -> str:
    """
    Build the prompt for the Strategy Planner node.

    Args:
        business_profile: Structured business information generated by
        the Input Parser node.

    Returns:
        A formatted prompt string for the Mistral model.
    """

    return f"""
You are a senior Indian marketing strategist.

Your task is to create the best marketing strategy for a small Indian business.

Business Profile:

{business_profile}

Business Goal:

{business_profile.get("goal")}

Occasion:

{business_profile.get("occasion")}

Rules:

- Return ONLY valid JSON.
- Do NOT include markdown.
- Do NOT include explanations.
- Do NOT include code fences.
- Keep every value concise.
- Choose the most suitable marketing angle.
- Consider Indian customers and buying behavior.
- Match the strategy to the campaign goal.

Return this exact JSON structure:

{{
    "tone": "",
    "campaign_angle": "",
    "hook": "",
    "urgency_level": "",
    "language_style": ""
}}
"""